version: '3.9'
services:
  backend:
    build: .
    image: web
    container_name: backend
    ports:
      - "5000:5000"
    command: python -m flask run -h 0.0.0.0
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery --app=app.celery worker
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis

  dashboard:
    build: .
    command: celery --app=app.celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
      - worker

  redis:
    image: "redis:6-alpine"